FROM docker.io/endlessm/eos:master
RUN export DEBIAN_FRONTEND=noninteractive && \
    apt-get update && \
    apt-get install -y build-essential && \
    apt-get build-dep -y shim && \
    apt-get clean
