FROM docker.io/endlessm/eos:master

RUN export DEBIAN_FRONTEND=noninteractive && \
    apt-get update && \
    apt-get install -y build-essential && \
    apt-get build-dep -y shim && \
    apt-get clean

LABEL org.opencontainers.image.source=https://github.com/endlessm/shim-review
LABEL org.opencontainers.image.description="Endless shim-review buildroot image"
LABEL org.opencontainers.image.licenses=GPL-2.0-or-later
